// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microsoft.Health.Fhir.Postgresql.Features.Storage;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Microsoft.Health.Fhir.Postgresql.Migrations
{
    [DbContext(typeof(PostgresqlFhirDatastoreContext))]
    [Migration("20191110170332_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Microsoft.Health.Fhir.Postgresql.Features.Schema.Entities.PgResource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime>("LastModified");

                    b.Property<List<string>>("LastModifiedClaims");

                    b.Property<string>("Resource")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResourceId");

                    b.Property<string>("ResourceType");

                    b.Property<double>("Version");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId", "Version")
                        .IsUnique();

                    b.ToTable("Resources");
                });
#pragma warning restore 612, 618
        }
    }
}
